In [4]:
import numpy as np

A=np.arange(1,251)
A=A.reshape((10,5,5))
A

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25]],

       [[ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75]],

       [[ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]],

       [[101, 102, 103, 104, 105],
        [106, 107, 108, 109, 110],
        [111, 112, 113, 114, 115],
        [116, 117, 118, 119, 120],
        [121, 122, 123, 124, 125]],

       [[126, 127, 128, 129, 130],
        [131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140],
        [1

In [51]:
def Determinant_3(arr):
    res=arr[0,0]*(arr[1,1]*arr[2,2]-arr[1,2]*arr[2,1])- \
        arr[0,1]*(arr[1,0]*arr[2,2]-arr[1,2]*arr[2,0])+ \
        arr[0,2]*(arr[1,0]*arr[2,1]-arr[1,1]*arr[2,0])
    return res

def Determinant_5(arr):
    res=np.ones((3,3))
    for i in range(3):
        for j in range(3):
            res[i,j]=Determinant_3(arr[i:i+3,j:j+3])
    return res

def Determinant_all(arr):
    res =np.ones((5,3,3))
    for i in range(5):
        res[i]=Determinant_5(A[i])
    return res



In [57]:
A_accum=np.multiply.accumulate(A.astype(np.float64))
A_accum



array([[[1.00000000e+00, 2.00000000e+00, 3.00000000e+00, 4.00000000e+00,
         5.00000000e+00],
        [6.00000000e+00, 7.00000000e+00, 8.00000000e+00, 9.00000000e+00,
         1.00000000e+01],
        [1.10000000e+01, 1.20000000e+01, 1.30000000e+01, 1.40000000e+01,
         1.50000000e+01],
        [1.60000000e+01, 1.70000000e+01, 1.80000000e+01, 1.90000000e+01,
         2.00000000e+01],
        [2.10000000e+01, 2.20000000e+01, 2.30000000e+01, 2.40000000e+01,
         2.50000000e+01]],

       [[2.60000000e+01, 5.40000000e+01, 8.40000000e+01, 1.16000000e+02,
         1.50000000e+02],
        [1.86000000e+02, 2.24000000e+02, 2.64000000e+02, 3.06000000e+02,
         3.50000000e+02],
        [3.96000000e+02, 4.44000000e+02, 4.94000000e+02, 5.46000000e+02,
         6.00000000e+02],
        [6.56000000e+02, 7.14000000e+02, 7.74000000e+02, 8.36000000e+02,
         9.00000000e+02],
        [9.66000000e+02, 1.03400000e+03, 1.10400000e+03, 1.17600000e+03,
         1.25000000e+03]],

      

In [56]:
A_accum=np.multiply.accumulate(A.astype(np.float64))
print(A_accum)


[[[1.00000000e+00 2.00000000e+00 3.00000000e+00 4.00000000e+00
   5.00000000e+00]
  [6.00000000e+00 7.00000000e+00 8.00000000e+00 9.00000000e+00
   1.00000000e+01]
  [1.10000000e+01 1.20000000e+01 1.30000000e+01 1.40000000e+01
   1.50000000e+01]
  [1.60000000e+01 1.70000000e+01 1.80000000e+01 1.90000000e+01
   2.00000000e+01]
  [2.10000000e+01 2.20000000e+01 2.30000000e+01 2.40000000e+01
   2.50000000e+01]]

 [[2.60000000e+01 5.40000000e+01 8.40000000e+01 1.16000000e+02
   1.50000000e+02]
  [1.86000000e+02 2.24000000e+02 2.64000000e+02 3.06000000e+02
   3.50000000e+02]
  [3.96000000e+02 4.44000000e+02 4.94000000e+02 5.46000000e+02
   6.00000000e+02]
  [6.56000000e+02 7.14000000e+02 7.74000000e+02 8.36000000e+02
   9.00000000e+02]
  [9.66000000e+02 1.03400000e+03 1.10400000e+03 1.17600000e+03
   1.25000000e+03]]

 [[1.32600000e+03 2.80800000e+03 4.45200000e+03 6.26400000e+03
   8.25000000e+03]
  [1.04160000e+04 1.27680000e+04 1.53120000e+04 1.80540000e+04
   2.10000000e+04]
  [2.4156000

In [58]:
b=Determinant_all(A_accum)
b

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])